-- ============================================================================
-- Development seed — LOCAL ONLY.
--
-- Applied by `supabase db reset` and by scripts/verify-migration.sh. Never
-- applied to a hosted project.
--
-- There is deliberately no catalogue data here any more. It moved to
-- supabase/migrations/20260919120000_demo_catalogue.sql, because the demo
-- catalogue now has to exist in production as well as locally, and a file the
-- migration pipeline never applies cannot put it there.
--
-- Two things went wrong with the old version of this file, and both are worth
-- recording so they are not reintroduced:
--
--   * It invented prices and printed them beside REAL retailer names. A
--     fabricated price attributed to a named shop is a false statement about
--     that shop, and it is the single claim a price-comparison site must never
--     make. The migration uses invented retailers on example.com instead.
--   * It was the only place `allow_mock_products` was ever set true, which
--     made "can the demo catalogue be seen?" a question about which file had
--     been run rather than about the database. The flag now lives with the
--     data that needs it.
--
-- Anything genuinely local-only — a throwaway account, a fixture for a bug
-- being chased — belongs here. Catalogue data does not.
-- ============================================================================

-- Intentionally empty.
